/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Pokedex2IndexRouteImport } from './routes/pokedex2/index'
import { Route as PokedexIndexRouteImport } from './routes/pokedex/index'
import { Route as ErrorIndexRouteImport } from './routes/error/index'
import { Route as PokedexPokemonNameRouteImport } from './routes/pokedex/$pokemonName'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Pokedex2IndexRoute = Pokedex2IndexRouteImport.update({
  id: '/pokedex2/',
  path: '/pokedex2/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokedexIndexRoute = PokedexIndexRouteImport.update({
  id: '/pokedex/',
  path: '/pokedex/',
  getParentRoute: () => rootRouteImport,
} as any)
const ErrorIndexRoute = ErrorIndexRouteImport.update({
  id: '/error/',
  path: '/error/',
  getParentRoute: () => rootRouteImport,
} as any)
const PokedexPokemonNameRoute = PokedexPokemonNameRouteImport.update({
  id: '/pokedex/$pokemonName',
  path: '/pokedex/$pokemonName',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pokedex/$pokemonName': typeof PokedexPokemonNameRoute
  '/error/': typeof ErrorIndexRoute
  '/pokedex/': typeof PokedexIndexRoute
  '/pokedex2/': typeof Pokedex2IndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pokedex/$pokemonName': typeof PokedexPokemonNameRoute
  '/error': typeof ErrorIndexRoute
  '/pokedex': typeof PokedexIndexRoute
  '/pokedex2': typeof Pokedex2IndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/pokedex/$pokemonName': typeof PokedexPokemonNameRoute
  '/error/': typeof ErrorIndexRoute
  '/pokedex/': typeof PokedexIndexRoute
  '/pokedex2/': typeof Pokedex2IndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/pokedex/$pokemonName'
    | '/error/'
    | '/pokedex/'
    | '/pokedex2/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pokedex/$pokemonName' | '/error' | '/pokedex' | '/pokedex2'
  id:
    | '__root__'
    | '/'
    | '/pokedex/$pokemonName'
    | '/error/'
    | '/pokedex/'
    | '/pokedex2/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PokedexPokemonNameRoute: typeof PokedexPokemonNameRoute
  ErrorIndexRoute: typeof ErrorIndexRoute
  PokedexIndexRoute: typeof PokedexIndexRoute
  Pokedex2IndexRoute: typeof Pokedex2IndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokedex2/': {
      id: '/pokedex2/'
      path: '/pokedex2'
      fullPath: '/pokedex2/'
      preLoaderRoute: typeof Pokedex2IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokedex/': {
      id: '/pokedex/'
      path: '/pokedex'
      fullPath: '/pokedex/'
      preLoaderRoute: typeof PokedexIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/error/': {
      id: '/error/'
      path: '/error'
      fullPath: '/error/'
      preLoaderRoute: typeof ErrorIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pokedex/$pokemonName': {
      id: '/pokedex/$pokemonName'
      path: '/pokedex/$pokemonName'
      fullPath: '/pokedex/$pokemonName'
      preLoaderRoute: typeof PokedexPokemonNameRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PokedexPokemonNameRoute: PokedexPokemonNameRoute,
  ErrorIndexRoute: ErrorIndexRoute,
  PokedexIndexRoute: PokedexIndexRoute,
  Pokedex2IndexRoute: Pokedex2IndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
